#!/bin/bash

# 🌳 Cursive Worktree Manager - Leveraging Git's native worktree feature
# for isolated theme development and testing

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Configuration
WORKTREE_BASE=".worktrees"
THEMES_DIR="themes"
CURRENT_BRANCH=$(git branch --show-current)

# Ensure we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}Error: Not in a git repository${NC}"
    exit 1
fi

# Create worktree base directory if it doesn't exist
mkdir -p "$WORKTREE_BASE"

# Function to create a new theme worktree
create_theme_worktree() {
    local theme_name="$1"
    local branch_name="theme/${theme_name}"
    local worktree_path="${WORKTREE_BASE}/theme-${theme_name}"
    
    echo -e "${CYAN}🌳 Creating worktree for theme: ${BOLD}${theme_name}${NC}"
    
    # Check if worktree already exists
    if git worktree list | grep -q "$worktree_path"; then
        echo -e "${YELLOW}⚠️  Worktree already exists for ${theme_name}${NC}"
        return 1
    fi
    
    # Create new branch and worktree
    if git show-ref --quiet "refs/heads/${branch_name}"; then
        # Branch exists, create worktree from it
        git worktree add "$worktree_path" "$branch_name"
    else
        # Create new branch with worktree
        git worktree add -b "$branch_name" "$worktree_path"
    fi
    
    # Set up theme-specific configuration
    setup_theme_config "$worktree_path" "$theme_name"
    
    echo -e "${GREEN}✅ Created worktree at: ${worktree_path}${NC}"
    echo -e "${GREEN}✅ Branch: ${branch_name}${NC}"
}

# Function to set up theme-specific git configuration
setup_theme_config() {
    local worktree_path="$1"
    local theme_name="$2"
    
    # Create theme directory structure
    mkdir -p "$worktree_path/$THEMES_DIR/$theme_name"
    
    # Create theme-specific git hooks
    mkdir -p "$worktree_path/.git/hooks"
    
    # Pre-commit hook for theme validation
    cat > "$worktree_path/.git/hooks/pre-commit" << 'EOF'
#!/bin/bash
# Cursive theme validation hook

theme_name=$(basename $(pwd) | sed 's/theme-//')
echo "🎨 Validating $theme_name theme..."

# Check for required theme files
if [ ! -f "themes/$theme_name/colors.sh" ]; then
    echo "❌ Missing colors.sh for theme $theme_name"
    exit 1
fi

# Validate ANSI color codes
if ! grep -q "export PS1" "themes/$theme_name/colors.sh"; then
    echo "❌ Missing PS1 export in theme configuration"
    exit 1
fi

echo "✅ Theme validation passed!"
EOF
    
    chmod +x "$worktree_path/.git/hooks/pre-commit"
    
    # Create commit message template
    cat > "$worktree_path/.git/commit-template.txt" << EOF
🎨 [$theme_name] 

# Theme: $theme_name
# Types: feat, fix, style, docs, test, refactor
# Example: 🎨 [vampires-letter] feat: Add blood-red syntax highlighting
EOF
    
    # Configure git for this worktree
    cd "$worktree_path"
    git config --local commit.template .git/commit-template.txt
    git config --local core.commentChar "#"
    cd - > /dev/null
    
    # Create initial theme structure
    create_theme_structure "$worktree_path" "$theme_name"
}

# Function to create initial theme structure
create_theme_structure() {
    local worktree_path="$1"
    local theme_name="$2"
    local theme_dir="$worktree_path/$THEMES_DIR/$theme_name"
    
    # Create theme configuration file
    cat > "$theme_dir/colors.sh" << EOF
#!/bin/bash
# 🎨 Cursive Terminal Theme: $theme_name
# Generated by Cursive Worktree Manager

# ANSI Color Definitions
export COLOR_BLACK="\\033[0;30m"
export COLOR_RED="\\033[0;31m"
export COLOR_GREEN="\\033[0;32m"
export COLOR_YELLOW="\\033[0;33m"
export COLOR_BLUE="\\033[0;34m"
export COLOR_MAGENTA="\\033[0;35m"
export COLOR_CYAN="\\033[0;36m"
export COLOR_WHITE="\\033[0;37m"

# Bright Colors
export COLOR_BRIGHT_BLACK="\\033[1;30m"
export COLOR_BRIGHT_RED="\\033[1;31m"
export COLOR_BRIGHT_GREEN="\\033[1;32m"
export COLOR_BRIGHT_YELLOW="\\033[1;33m"
export COLOR_BRIGHT_BLUE="\\033[1;34m"
export COLOR_BRIGHT_MAGENTA="\\033[1;35m"
export COLOR_BRIGHT_CYAN="\\033[1;36m"
export COLOR_BRIGHT_WHITE="\\033[1;37m"

# Theme-specific prompt
export PS1="\\[\\e[3m\\]\\[\${COLOR_CYAN}\\]\\u\\[\${COLOR_WHITE}\\]@\\[\${COLOR_MAGENTA}\\]\\h\\[\${COLOR_WHITE}\\]:\\[\${COLOR_YELLOW}\\]\\w\\[\${COLOR_WHITE}\\]\\$ \\[\\e[0m\\]"

# Theme metadata
export THEME_NAME="$theme_name"
export THEME_CATEGORY="custom"
export THEME_DESCRIPTION="Custom theme created in isolated worktree"
EOF
    
    # Create theme README
    cat > "$theme_dir/README.md" << EOF
# 🎨 $theme_name Theme

A custom Cursive Terminal theme developed in an isolated Git worktree.

## Features
- Isolated development environment
- Version-controlled theme changes
- Easy testing without affecting main branch

## Usage
\`\`\`bash
# Apply this theme
source $THEMES_DIR/$theme_name/colors.sh
\`\`\`

## Development
This theme is being developed in worktree: \`$worktree_path\`
EOF
    
    # Create demo script
    cat > "$theme_dir/demo.sh" << 'EOF'
#!/bin/bash
# Demo script for theme testing

source "$(dirname "$0")/colors.sh"

echo -e "${COLOR_CYAN}${BOLD}🎨 Theme Demo: ${THEME_NAME}${NC}"
echo -e "${COLOR_GREEN}✓ Success message${NC}"
echo -e "${COLOR_YELLOW}⚠ Warning message${NC}"
echo -e "${COLOR_RED}✗ Error message${NC}"
echo -e "${COLOR_MAGENTA}★ Special highlight${NC}"
echo -e "${COLOR_BLUE}ℹ Information${NC}"
EOF
    
    chmod +x "$theme_dir/demo.sh"
}

# Function to list all theme worktrees
list_theme_worktrees() {
    echo -e "${CYAN}${BOLD}🌳 Active Theme Worktrees:${NC}"
    echo
    
    local found=0
    while IFS= read -r line; do
        if [[ "$line" =~ $WORKTREE_BASE/theme- ]]; then
            local path=$(echo "$line" | awk '{print $1}')
            local commit=$(echo "$line" | awk '{print $2}')
            local branch=$(echo "$line" | awk '{print $3}' | tr -d '[]')
            local theme_name=$(basename "$path" | sed 's/theme-//')
            
            echo -e "${GREEN}Theme:${NC} ${BOLD}$theme_name${NC}"
            echo -e "  ${BLUE}Path:${NC} $path"
            echo -e "  ${YELLOW}Branch:${NC} $branch"
            echo -e "  ${MAGENTA}Commit:${NC} ${commit:0:7}"
            echo
            found=1
        fi
    done < <(git worktree list)
    
    if [ $found -eq 0 ]; then
        echo -e "${YELLOW}No theme worktrees found.${NC}"
    fi
}

# Function to switch to a theme worktree
switch_to_theme() {
    local theme_name="$1"
    local worktree_path="${WORKTREE_BASE}/theme-${theme_name}"
    
    if [ ! -d "$worktree_path" ]; then
        echo -e "${RED}Error: Worktree for theme '${theme_name}' not found${NC}"
        return 1
    fi
    
    echo -e "${CYAN}Switching to theme worktree: ${BOLD}${theme_name}${NC}"
    cd "$worktree_path"
    echo -e "${GREEN}✅ Now in: $(pwd)${NC}"
    
    # Show theme status
    echo
    echo -e "${YELLOW}Theme Status:${NC}"
    git status --short
}

# Function to test a theme in its worktree
test_theme() {
    local theme_name="$1"
    local worktree_path="${WORKTREE_BASE}/theme-${theme_name}"
    
    if [ ! -d "$worktree_path" ]; then
        echo -e "${RED}Error: Worktree for theme '${theme_name}' not found${NC}"
        return 1
    fi
    
    echo -e "${CYAN}🧪 Testing theme: ${BOLD}${theme_name}${NC}"
    
    # Run theme demo
    if [ -f "$worktree_path/$THEMES_DIR/$theme_name/demo.sh" ]; then
        bash "$worktree_path/$THEMES_DIR/$theme_name/demo.sh"
    else
        echo -e "${YELLOW}No demo script found${NC}"
    fi
    
    # Apply theme temporarily
    echo
    echo -e "${CYAN}Applying theme to current shell...${NC}"
    source "$worktree_path/$THEMES_DIR/$theme_name/colors.sh"
    echo -e "${GREEN}✅ Theme applied! Your prompt should now use the ${theme_name} theme.${NC}"
}

# Function to merge theme back to main branch
merge_theme() {
    local theme_name="$1"
    local branch_name="theme/${theme_name}"
    
    echo -e "${CYAN}📥 Merging theme: ${BOLD}${theme_name}${NC}"
    
    # Save current branch
    local current=$(git branch --show-current)
    
    # Switch to main branch
    git checkout main
    
    # Merge theme branch
    echo -e "${YELLOW}Merging ${branch_name} into main...${NC}"
    if git merge "$branch_name" --no-ff -m "🎨 Merge theme: $theme_name"; then
        echo -e "${GREEN}✅ Successfully merged ${theme_name} theme${NC}"
    else
        echo -e "${RED}❌ Merge conflict detected. Please resolve manually.${NC}"
        return 1
    fi
    
    # Return to original branch
    git checkout "$current"
}

# Function to clean up a theme worktree
remove_theme_worktree() {
    local theme_name="$1"
    local worktree_path="${WORKTREE_BASE}/theme-${theme_name}"
    local branch_name="theme/${theme_name}"
    
    echo -e "${CYAN}🗑️  Removing worktree for theme: ${BOLD}${theme_name}${NC}"
    
    # Check if worktree exists
    if ! git worktree list | grep -q "$worktree_path"; then
        echo -e "${RED}Error: Worktree not found${NC}"
        return 1
    fi
    
    # Confirm removal
    read -p "Are you sure you want to remove this worktree? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Cancelled${NC}"
        return 0
    fi
    
    # Remove worktree
    git worktree remove "$worktree_path"
    echo -e "${GREEN}✅ Removed worktree${NC}"
    
    # Ask about branch deletion
    read -p "Delete the branch '$branch_name' as well? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git branch -d "$branch_name" 2>/dev/null || git branch -D "$branch_name"
        echo -e "${GREEN}✅ Deleted branch${NC}"
    fi
}

# Function to show worktree-based workflow
show_workflow() {
    cat << 'EOF'
🌳 Cursive Theme Development Workflow with Git Worktrees

1. Create Theme Worktree:
   ./cursive-worktree-manager.sh create <theme-name>
   
2. Develop Theme:
   ./cursive-worktree-manager.sh switch <theme-name>
   # Edit theme files, test changes
   git add .
   git commit -m "🎨 [theme-name] Your changes"
   
3. Test Theme:
   ./cursive-worktree-manager.sh test <theme-name>
   
4. Merge to Main:
   ./cursive-worktree-manager.sh merge <theme-name>
   
5. Clean Up:
   ./cursive-worktree-manager.sh remove <theme-name>

Benefits:
✅ Isolated theme development
✅ Parallel theme work
✅ Clean git history
✅ Easy testing without affecting main
✅ Native git integration

EOF
}

# Main command handler
case "$1" in
    create)
        if [ -z "$2" ]; then
            echo -e "${RED}Error: Please provide a theme name${NC}"
            echo "Usage: $0 create <theme-name>"
            exit 1
        fi
        create_theme_worktree "$2"
        ;;
    list)
        list_theme_worktrees
        ;;
    switch)
        if [ -z "$2" ]; then
            echo -e "${RED}Error: Please provide a theme name${NC}"
            echo "Usage: $0 switch <theme-name>"
            exit 1
        fi
        switch_to_theme "$2"
        ;;
    test)
        if [ -z "$2" ]; then
            echo -e "${RED}Error: Please provide a theme name${NC}"
            echo "Usage: $0 test <theme-name>"
            exit 1
        fi
        test_theme "$2"
        ;;
    merge)
        if [ -z "$2" ]; then
            echo -e "${RED}Error: Please provide a theme name${NC}"
            echo "Usage: $0 merge <theme-name>"
            exit 1
        fi
        merge_theme "$2"
        ;;
    remove)
        if [ -z "$2" ]; then
            echo -e "${RED}Error: Please provide a theme name${NC}"
            echo "Usage: $0 remove <theme-name>"
            exit 1
        fi
        remove_theme_worktree "$2"
        ;;
    workflow)
        show_workflow
        ;;
    *)
        echo -e "${CYAN}${BOLD}🌳 Cursive Worktree Manager${NC}"
        echo
        echo "Usage: $0 <command> [options]"
        echo
        echo "Commands:"
        echo "  create <theme>  - Create a new theme worktree"
        echo "  list           - List all theme worktrees"
        echo "  switch <theme> - Switch to a theme worktree"
        echo "  test <theme>   - Test a theme in its worktree"
        echo "  merge <theme>  - Merge theme back to main branch"
        echo "  remove <theme> - Remove a theme worktree"
        echo "  workflow       - Show the recommended workflow"
        echo
        echo "Example:"
        echo "  $0 create cosmic-dreams"
        echo "  $0 test cosmic-dreams"
        echo "  $0 merge cosmic-dreams"
        ;;
esac