# GitHub Pages configuration
theme: null
title: Cursive Terminal Themes
description: 33 Beautiful Themes for Your Cursive Coding Experience
baseurl: "/Cursive-Terminal"
url: "https://midnightnow.github.io"